default_language_version:
  python: python3.8

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --preview
        pass_filenames: true
        language: system
        types: [python]
